djangostart/apps/forms_base/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^register/$',views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
]

djangostart/djangostart/urls.py
from django.conf.urls import url, include, handler404, handler500
from django.contrib import admin
from app001 import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^test/$', views.test),
    url(r'^demo/$', views.demo_form,name="demo"),
    url(r'^demo2/$', views.demo_form2),
    url(r'^demo_login/$', views.demo_db),
    url(r'^demo_register/$', views.demo_register),
    url(r'^index/$', views.demo_index),

    url('^route_base/', include('apps.route_base.urls', namespace='route_base')),
    url('^route_resolve/', include('apps.route_resolve.urls', namespace='route_resolve')),
    url('^django_templates/', include('apps.django_templates.urls', namespace='django_templates')),
    url(r'^forms_base/', include('apps.forms_base.urls', namespace='forms_base')),
    url(r'^forms_auth/', include('apps.forms_auth.urls', namespace='forms_auth')),
    url(r'^django_view/', include('apps.django_view.urls', namespace='django_view'))


]


handler404 = views.my404
handler500 = views.my500

djangostart/apps/forms_base/models.py
from django.db import models
import json
# Create your models here.


class UserInfo(models.Model):
    username = models.CharField(verbose_name="用户名", max_length=18)
    password = models.CharField(verbose_name="密码", max_length=128)

    def __str__(self):
        return self.username

    # 自定义方法
    def to_dict(self):
        return dict([(attr, getattr(self, attr)) for attr in [f.name for f in self._meta.fields]])

    # 定义元数据 --> 显示类
    class Meta:
        verbose_name = "用户列表"
        verbose_name_plural = verbose_name

djangostart/apps/forms_base/forms.py
"""authot:
   data:
"""
from django import forms
from . import models


# 定义一个表单
class ContactForm(forms.Form):
    # 一个属性就是一个表单元素
    # forms.CharField 字段类型
    '''
        label  设置标题
        required  True默认必填项
        min_length  内容最短长度
        initial  初始化的值
        error_messages 设置错误提示信息，后端验证error
    '''
    # widgets 小部件
    subject = forms.CharField(label="主题",
                              min_length=9,
                              # required=True,
                              # initial="Django-Form",
                              error_messages={
                                  "min_length":"主题最少为8字符",
                                  "required":"主题是必填项",
                              })

    content2 = forms.CharField(label="正文2",
                               widget=forms.Textarea(
                                        attrs={
                                            "name":"content2",
                                            "class":"class",
                                            "style":"color:red;font-size:20px",
                                            "cols":20,
                                        }
                                    )


                               )

    sender = forms.EmailField(label="发送人")
    cc_myself = forms.BooleanField(label="抄送")
    # 密码字段
    password = forms.CharField(label="密码", widget=forms.PasswordInput)
    # 单radio值为字符串
    gender = forms.fields.ChoiceField(
        choices=((1,"男"),(2,"女"),(3,"保密")),
        label="性别",
        initial=3,
        widget=forms.widgets.RadioSelect(),
    )



# 通过django.forms定义表单

class RegisterForm(forms.ModelForm):
    """注册表单"""
    # 因为Model中的元素默认是会把密码显示出来的，所以在这里重新定义一个password
    password1 = forms.CharField(label="输入密码", max_length=18, widget=forms.PasswordInput)
    password2 = forms.CharField(label="确认密码", max_length=18, widget=forms.PasswordInput)
    class Meta:
        model = models.UserInfo
        # 将model UserInfo中的字段生成到表单
        # exclude表示排除哪个字段，fields表示包含哪个字段， 两个选项必须选其一
        # exclude = ()
        fields = ('username', 'password')

    def clean_username(self):
        """
        对username字段做检查用户名是否已经被注册
        注意字段一定要有返回值
        """
        # self.cleaned_data["username"] => 获取表单提交的username数据
        users = models.UserInfo.objects.filter(username=self.cleaned_data["username"])
        if not users:
            return self.cleaned_data["username"]
        else:
            raise forms.ValidationError("该用户名已经被使用")

    def clean(self):
        """
        验证两次输入的密码是否一次
        对整个表单验证时，不需要返回值
        """
        if self.cleaned_data["password"] != self.cleaned_data["password2"]:
            raise forms.ValidationError("密码不一致！")


class LoginForm(forms.ModelForm):
    """登录表单"""
    password = forms.CharField(label="密码", max_length=30, widget=forms.PasswordInput(attrs={"size": 20, }))

    def clean_username(self):
        user = models.UserInfo.objects.filter(username__iexact=self.cleaned_data["username"])
        if not user:
            raise forms.ValidationError("用户不存在")
        else:
            return self.cleaned_data["username"]

    class Meta:
        model = models.UserInfo
        exclude = ()

djangostart/apps/forms_base/views.py
from django.shortcuts import render, HttpResponse
from django.contrib.auth.hashers import make_password, check_password
from django.contrib import messages
from .forms import ContactForm, RegisterForm, LoginForm
from .models import UserInfo


# Create your views here.
def index(request):
    contact_form = ContactForm(request.GET)
    return render(request, "forms_base/index.html", {"form":contact_form})

def register(request):
    # 没有绑定数据的表单
    reg_form = RegisterForm()
    if request.method == 'POST':
        #绑定数据的表单
        reg_form = RegisterForm(request.POST)
        if reg_form.is_valid():
            # is_valid => 用来验证表单中的所有数据中否都合法
            # 验证用户名：检查用户是否已经在数据中存在，可以对某个字段来验证
            # 给某个字段添加验证方法:定义form的时候，clean_字段名
            # 给整个表单添加验证方法：定义form的时候，加一个clean方法
            username = reg_form.cleaned_data["username"]
            password = reg_form.cleaned_data["password"]
            password = make_password(password)
            UserInfo.objects.create(username=username, password=password)
            print("合法")
        else:
            print("不合法")
    return render(request, 'forms_base/register.html', {"form":reg_form})

def login(request):
    login_form = LoginForm()
    if request.method == "POST":
        login_form = LoginForm(request.POST)
        # is_valid提交的数据合法(会检查所有字段及表单整体的合法性)
        if login_form.is_valid():
            password = login_form.cleaned_data["password"]
            # user = UserInfo.objects.get(username=login_form.cleaned_data["username"]).to_dict()
            user = UserInfo.objects.get(username=login_form.cleaned_data["username"])
            # user.password => 密文
            # password => 明文
            if check_password(password, user.password):
                # 验证成功，登录
                print("用户名密码验证成功")
                # 注意需要把user对象需要能被序列化（json格式）
                request.session['user'] = user.username
                # 1. 生成一个随机的sessionid字符串
                # 2. 将sessionid和键值,对保存到本地
                # 3. 通过cookie将sessionid保存到客户端
                # 4. 只可以通过sesssionid来判断当前是哪个用户登录
            else:
                # 验证失败
                messages.add_message(request, messages.INFO, "用户名密码验证失败")
                print("用户名密码验证失败")
    return render(request, 'forms_base/login.html', {"form": login_form})


def logout(request):
    print('退出成功')
    return HttpResponse("退出成功")

djangostart/apps/forms_base/templates/forms_base/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
</head>
<body>
<div class="container-fluid">
{#    <form class="form-inline">#}
{#        <div class="form-group">#}
{#            <label class="sr-only" for="exampleInputEmail3">Email address</label>#}
{#            <input type="email" class="form-control" id="exampleInputEmail3" placeholder="Email">#}
{#        </div>#}
{#        <div class="form-group">#}
{#            <label class="sr-only" for="exampleInputPassword3">Password</label>#}
{#            <input type="password" class="form-control" id="exampleInputPassword3" placeholder="Password">#}
{#        </div>#}
{#        <div class="checkbox">#}
{#            <label><input type="checkbox"> Remember me</label>#}
{#        </div>#}
{#        <button type="submit" class="btn btn-default">Sign in</button>#}
{#    </form>#}
    <form action="/your-name/" method="post">
	<p><label for="id_subject">Subject:</label>
	    <input id="id_subject" type="text" name="subject" maxlength="100" required /></p>
	<p><label for="id_message">Message:</label>
	    <textarea name="message" id="id_message" required></textarea></p>
	<p><label for="id_sender">Sender:</label>
	    <input type="email" name="sender" id="id_sender" required /></p>
	<p><label for="id_cc_myself">Cc myself:</label>
	    <input type="checkbox" name="cc_myself" id="id_cc_myself" /></p>
    </form>
    <form>1.
        {{ form.as_table }}
        <button type="submit">提交</button>
    </form>
{#    2.{{ form.as_p }}#}
{#    3.{{ form.as_ul }}/#}
    {{ form.subject.label }}:{{ form.subject }}:{{ form.subject.errors.0 }}:{{ form.subject.errors }}
</div>
</body>
</html>

djangostart/apps/forms_base/templates/forms_base/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>欢迎你！{{ request.session.user }}</h1>
{% if messages %}
    {% for item in messages %}
        {{ item }}-----
    {% endfor %}
{% endif %}
<ul>
    <li><a href="{% url 'forms_base:register' %}">注册</a></li>
    <li><a href="{% url 'forms_base:login' %}">登录</a></li>
    <li><a href="{% url 'forms_base:logout' %}">注销</a></li>
    <li><a href="{% url 'forms_base:index' %}">首页</a></li>
</ul>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="登录">
</form>
</body>
</html>

djangostart/apps/forms_base/templates/forms_base/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>欢迎你！{{ request.session.user }}</h1>
<ul>
    <li><a href="{% url 'forms_base:register' %}">注册</a></li>
    <li><a href="{% url 'forms_base:login' %}">登录</a></li>
    <li><a href="{% url 'forms_base:logout' %}">注销</a></li>
    <li><a href="{% url 'forms_base:index' %}">首页</a></li>
</ul>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="注册">
</form>
</body>
</html>